<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/2.preliminaries/2_1_data_manipulation_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 4, 5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [11]:
torch.randn(3, 4)

tensor([[-0.9529, -1.5216, -0.9174,  0.3298],
        [ 1.3601, -0.2283,  0.0079,  0.5566],
        [-0.7107,  2.2616,  0.0053,  0.1172]])

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [13]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [14]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [15]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [19]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [21]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [22]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [23]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [25]:
print(X.sum())

tensor(66.)


In [26]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [27]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
X[:,0]

tensor([0., 4., 8.])

In [31]:
X[:,0:2]

tensor([[0., 1.],
        [4., 5.],
        [8., 9.]])

In [32]:
X[1,3]

tensor(7.)

In [33]:
befor = id(Y)
Y = Y + X
after = id(Y)
befor == after

False

In [34]:
befor = id(Y)
Y[:] = Y + X
after = id(Y)
befor == after

True

In [35]:
befor = id(Y)
Y += X
after = id(Y)
befor == after

True

In [36]:
A = X.numpy()
B = torch.from_numpy(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)