<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/2.preliminaries/2_3_%1Dlinear_%1Dalgebra_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[1]

tensor(1)

In [4]:
len(x), x.shape

(4, torch.Size([4]))

In [5]:
A = torch.arange(20).reshape(5,-1)

In [6]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A[0,:]

tensor([0, 1, 2, 3])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
A + B

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])

In [12]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [13]:
A.sum(axis=0)

tensor([40, 45, 50, 55])

In [14]:
A.sum(axis=1)

tensor([ 6, 22, 38, 54, 70])

In [17]:
A.sum(axis=1, keepdim=True)

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

In [20]:
x = torch.tensor([0, 1, 2, 3])
print(x)

tensor([0, 1, 2, 3])


In [21]:
y = torch.tensor([1, 1, 1, 1])
y

tensor([1, 1, 1, 1])

In [22]:
x @ y

tensor(6)

In [23]:
torch.dot(x, y)

tensor(6)

In [24]:
A, A.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]), torch.Size([5, 4]))

In [25]:
x, x.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [26]:
A @ x

tensor([ 14,  38,  62,  86, 110])

In [27]:
torch.mv(A, x)

tensor([ 14,  38,  62,  86, 110])

In [30]:
B = torch.ones(4, 3, dtype=torch.long)

In [31]:
A @ B

tensor([[ 6,  6,  6],
        [22, 22, 22],
        [38, 38, 38],
        [54, 54, 54],
        [70, 70, 70]])

In [33]:
torch.mm(A, B)

tensor([[ 6,  6,  6],
        [22, 22, 22],
        [38, 38, 38],
        [54, 54, 54],
        [70, 70, 70]])

In [34]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [35]:
torch.abs(u).sum()

tensor(7.)

In [38]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)

In [39]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
torch.norm(A)

tensor(22.4944)

In [41]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
A.T.T

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])