<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/2.preliminaries/2_3_%1Dlinear_%1Dalgebra_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
x = tf.constant(3.0)
y = tf.constant(2.0)

In [4]:
x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

In [5]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [6]:
len(x)

4

In [7]:
x.shape

TensorShape([4])

In [8]:
A = tf.reshape(tf.range(20), (5, 4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [9]:
A[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [11]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]], dtype=int32)>

In [12]:
X = tf.reshape(tf.range(24), (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [13]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5, 4))

In [14]:
id(A)

139743789094672

In [15]:
B = A
id(B)

139743789094672

In [16]:
A + B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.],
       [32., 34., 36., 38.]], dtype=float32)>

In [17]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

In [34]:
x = tf.range(4, dtype=tf.float32)
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [19]:
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=float32, numpy=190.0>

In [20]:
tf.reduce_sum(A, axis=0)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>

In [21]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>

In [22]:
tf.reduce_sum(A, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[40., 45., 50., 55.]], dtype=float32)>

In [23]:
tf.reduce_sum(A, axis=1, keepdims=True)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [42]:
y = tf.ones(4, dtype=tf.float32)
tf.tensordot(x, y, axes=0)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]], dtype=float32)>

In [43]:
x.shape

TensorShape([4])

In [44]:
y.shape

TensorShape([4])

In [50]:
A.shape

TensorShape([5, 4])

In [51]:
x.shape

TensorShape([4])

In [52]:
tf.linalg.matvec(A, x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>

In [53]:
B = tf.ones((4, 3), tf.float32)

In [54]:
B.shape

TensorShape([4, 3])

In [55]:
C = tf.matmul(A, B)

In [56]:
C.shape

TensorShape([5, 3])

In [57]:
u = tf.constant([3.0, -4.0])

In [58]:
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>