<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/2.preliminaries/2_5_automatic_differentiation_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
print(x.grad)

None


In [4]:
y = 2 * x @ x.T

In [5]:
y

tensor(28., grad_fn=<DotBackward0>)

In [6]:
y.backward()
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [7]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [8]:
print(x.grad)

tensor([0., 0., 0., 0.])


In [9]:
y = x.sum()

In [10]:
y.backward()

In [11]:
print(x.grad)

tensor([1., 1., 1., 1.])


In [12]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [13]:
y = x * x

In [14]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [15]:
y.backward(torch.ones(4))

In [16]:
print(x.grad)

tensor([0., 2., 4., 6.])


In [17]:
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

In [20]:
a = torch.randn(size=(), requires_grad=True)

In [22]:
d = f(a)

In [23]:
d

tensor(1980.8055, grad_fn=<MulBackward0>)

In [24]:
d.backward()

In [25]:
a.grad

tensor(2048.)