<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/2.preliminaries/2_5_automatic_differentiation_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(4, dtype=tf.float32)

In [3]:
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [4]:
x = tf.Variable(x)

In [7]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [10]:
with tf.GradientTape() as t:
  y = 2 * tf.tensordot(x, x, axes = 1)

In [12]:
x_grad = t.gradient(y, x)

In [13]:
with tf.GradientTape() as t:
  y = tf.reduce_sum(x)
t.gradient(y, x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [16]:
y = tf.reduce_sum(x)

In [17]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [18]:
with tf.GradientTape() as t:
  y = x * x
t.gradient(y, x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 2., 4., 6.], dtype=float32)>

In [19]:
def f(a):
  b = a * 2
  while tf.norm(b) < 1000:
    b = b * 2
  if tf.reduce_sum(b) > 0:
    c = b
  else:
    c = 100 * b
  return c

In [20]:
a = tf.Variable(tf.random.normal(shape=()))

In [22]:
with tf.GradientTape() as t:
    d = f(a)
d_grad = t.gradient(d, a)
d_grad

<tf.Tensor: shape=(), dtype=float32, numpy=409600.0>