<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/6.convolutional_neural_networks/6_4_multiple_input_and_multiple_output_channels_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch

In [22]:
def corr2d(X, K):
    """Compute 2D cross-correlation."""
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

In [23]:
def corr2d_multi_in(X, K):

  return sum(corr2d(x, k) for x,k in zip(X, K))

In [24]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])

K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

In [25]:
corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [26]:
def corr2d_multi_in_out(X, K):

  return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

In [27]:
K = torch.stack((K, K + 1, K + 2), 0)
K.shape

torch.Size([3, 2, 2, 2])

In [28]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [29]:
def corr2d_multi_in_out_1x1(X, K):
  
  c_i, h, w = X.shape
  c_o = K.shape[0]
  X = X.reshape((c_i, h * w))
  K = K.reshape((c_o, c_i))
  Y = torch.matmul(K, X)
  return Y.reshape((c_o, h, w))

In [30]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)

In [31]:
Y1

tensor([[[ 0.0844, -1.2110,  0.3370],
         [ 1.2762, -2.1343, -0.4387],
         [-2.0156, -0.6945, -0.3993]],

        [[-2.7220, -3.1078, -0.5832],
         [ 1.2223, -4.7143, -0.2694],
         [-5.8174, -0.5088,  1.7955]]])