<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/6.convolutional_neural_networks/6_5_pooling_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import tensorflow as tf

In [15]:
def pool2d(X, pool_size, mode='max'):
  p_h, p_w = pool_size
  Y = tf.Variable(tf.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w +1)))
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      if mode == 'max':
        Y[i, j].assign(tf.reduce_max(X[i: i + p_h, j: j + p_w]))
      elif mode =='avg':
        Y[i, j].assign(tf.reduce_mean(X[i: i + p_h, j: j + p_w]))
  return Y

In [16]:
X = tf.constant([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[4., 5.],
       [7., 8.]], dtype=float32)>

In [17]:
pool2d(X, (2, 2), 'avg')

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [18]:
X = tf.reshape(tf.range(16, dtype=tf.float32), (1, 4, 4, 1))
X

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [19]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3])
pool2d(X)

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[10.]]]], dtype=float32)>

In [20]:
paddings = tf.constant([[0, 0], [1,0], [1,0], [0,0]])

In [21]:
X_padded = tf.pad(X, paddings, "CONSTANT")

In [22]:
X_padded

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 0.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 0.],
         [ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[ 0.],
         [12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [23]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3], padding='valid',
                                   strides=2)
pool2d(X_padded)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.],
         [ 7.]],

        [[13.],
         [15.]]]], dtype=float32)>

In [24]:
paddings = tf.constant([[0, 0], [0, 0], [1, 1], [0, 0]])
X_padded = tf.pad(X, paddings, "CONSTANT")

In [25]:
X_padded

<tf.Tensor: shape=(1, 4, 6, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 0.],
         [ 1.],
         [ 2.],
         [ 3.],
         [ 0.]],

        [[ 0.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 0.]],

        [[ 0.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [ 0.]],

        [[ 0.],
         [12.],
         [13.],
         [14.],
         [15.],
         [ 0.]]]], dtype=float32)>

In [26]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[2, 3], padding='valid',
                                   strides=(2, 3))
pool2d(X_padded)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.],
         [ 7.]],

        [[13.],
         [15.]]]], dtype=float32)>

In [27]:
X = tf.concat([X, X + 1], 3)

In [29]:
X.shape

TensorShape([1, 4, 4, 2])

In [30]:
paddings = tf.constant([[0, 0], [1,0], [1,0], [0,0]])
X_padded = tf.pad(X, paddings, "CONSTANT")
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3], padding='valid',
                                   strides=2)
pool2d(X_padded)

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[ 5.,  6.],
         [ 7.,  8.]],

        [[13., 14.],
         [15., 16.]]]], dtype=float32)>