<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/5.deep_learning_computation/5_4_custom_layers_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

In [7]:
class CenteredLayer(tf.keras.Model):

  def __init__(self):
    super().__init__()
  
  def call(self, inputs):
    return inputs - tf.reduce_mean(inputs)

In [8]:
layer = CenteredLayer()
layer(tf.constant([1, 2, 3, 4, 5]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-2, -1,  0,  1,  2], dtype=int32)>

In [12]:
net = tf.keras.Sequential([tf.keras.layers.Dense(128), CenteredLayer()])

In [16]:
Y = net(tf.random.uniform((4, 8)))
tf.reduce_mean(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.1909516e-09>

In [17]:
class MyDense(tf.keras.Model):
  def __init__(self, units):
    super().__init__()
    self.units = units
  
  def build(self, X_shape):
    self.weight = self.add_weight(name='weight', shape=[X_shape[-1], self.units], initializer=tf.random_normal_initializer())
    self.bias = self.add_weight(name='bias', shape=[self.units], initializer=tf.zeros_initializer())

  def call(self, X):
    linear = tf.matmul(X, self.weight) + self.bias
    return tf.nn.relu(linear)

In [18]:
dense = MyDense(3)
dense(tf.random.uniform((2, 5)))

dense.get_weights()

[array([[ 0.05763143,  0.05863529,  0.16805494],
        [ 0.02128346,  0.01650102,  0.05532798],
        [-0.02324388,  0.00493372,  0.02443931],
        [ 0.02694551,  0.00286757, -0.05841271],
        [ 0.00345064, -0.05094113,  0.05466669]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [19]:
dense(tf.random.uniform((2, 5)))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.06442121, 0.03420042, 0.11466269],
       [0.08079169, 0.01374883, 0.16529599]], dtype=float32)>

In [20]:
net = tf.keras.models.Sequential([MyDense(8), MyDense(1)])
net(tf.random.uniform((2, 64)))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.02155964],
       [0.00068316]], dtype=float32)>