<a href="https://colab.research.google.com/github/thai94/d2l/blob/main/5.deep_learning_computation/5_4_custom_layers_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
from torch import nn
from torch.nn import functional as F

In [21]:
class CenteredLayer(nn.Module):

  def __init__(self):
    super().__init__()

  def forward(self, X):
    return X - X.mean()

In [22]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [23]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [24]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(4.6566e-10, grad_fn=<MeanBackward0>)

In [25]:
class MyLinear(nn.Module):
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units))
    self.bias = nn.Parameter(torch.randn(units,))

  def forward(self, X):
    linear = torch.matmul(X, self.weight.data) + self.bias.data
    return F.relu(linear)

In [26]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.6300,  1.5228, -2.9039],
        [ 0.8846, -0.3136, -1.3014],
        [ 1.6339,  1.3082, -1.0273],
        [ 1.3609, -0.5571,  1.0084],
        [ 0.5612, -0.7647,  1.8623]], requires_grad=True)

In [27]:
linear(torch.rand(2, 5))

tensor([[3.2267, 0.0000, 0.3253],
        [3.5691, 0.3921, 0.0000]])

In [28]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.5568],
        [3.2691]])